### ISSUE TITLE
Export functionality

### ISSUE THREAD

**Issue by anissen** [FuzzyWuzzie/LuxeParticleDesigner#2]
It would be really nice to be able to somehow export the settings. This would allow users to quickly replicate the designed particle system in another Luxe project.

**Comment by hamaluik** [comment]
Good idea, working on that now.

**Comment by hamaluik** [comment]
Added half of this in daee931e2a56aa855d669c0e416cdfe4b29afdcb, need to implement loading from the resulting JSON
